---

- name: install necessary packages
  apt:
    name: samba
    state: present

- name: create mount point
  file:
    path: "/srv/share/"
    state: directory

- name: mount external drive
  mount:
    path: /srv/share
    src: /dev/sdb1
    fstype: ntfs
    state: mounted

- name: configure samba
  template:
    src: smb.j2
    dest: /etc/samba/smb.conf
  notify:
    - restart samba

- name: enable samba service
  systemd:
    name: smbd
    state: started
    enabled: yes

- name: stop transmission
  systemd:
    name: transmission-daemon
    state: stopped

- name: change transmission dl directory to share
  template:
    src: transmission.j2
    dest: /etc/transmission-daemon/settings.json

- name: start transmission daemon
  systemd:
    name: transmission-daemon
    state: started
    enabled: yes
