- name: restart dhcpcd
  service:
    name: dhcpcd
    daemon_reload: yes
    state: restarted

- name: restart hostapd
  service:
    name: hostapd
    state: restarted

- name: restart dnsmasq
  service:
    name: dnsmasq
    state: restarted

- name: restart sysctl
  shell: echo 1 > /proc/sys/net/ipv4/ip_forward
